/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente.ui.gui.EcraInicial;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Cliente.logic.ObservableGame;

/**
 *
 * @author Tiago Coutinho
 */
public class Login extends javax.swing.JPanel {

    ObservableGame ObservableGame;
    boolean UserFirst = true, PassFirst = true;
    JPanel CardPanel;
    RegistoLoginView RegistoLoginView;
    
    public Login() {
        initComponents();
    }

    Login(ObservableGame ObservableGame) {
        this.ObservableGame = ObservableGame;
        initComponents();
        jErro.setVisible(false);
        jPassword.setEchoChar((char) 0);
    }

    public void setCardPanel(JPanel J) {
        CardPanel = J;
    }
    
        
        
    public void setRegistoLoginView(RegistoLoginView v)
    {
        RegistoLoginView=v;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jUsername = new javax.swing.JTextField();
        jEntrar = new javax.swing.JButton();
        jErro = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();

        jPasswordField1.setText("jPasswordField1");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setText("Login");

        jUsername.setForeground(new java.awt.Color(204, 204, 204));
        jUsername.setText("Username");
        jUsername.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jUsername.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                jUsernameFocusGained(evt);
            }
        });
        jUsername.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jUsernameMouseClicked(evt);
            }
        });
        jUsername.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jUsernameActionPerformed(evt);
            }
        });

        jEntrar.setText("Entrar");
        jEntrar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jEntrarMouseClicked(evt);
            }
        });
        jEntrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jEntrarActionPerformed(evt);
            }
        });

        jErro.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jErro.setForeground(new java.awt.Color(153, 0, 0));
        jErro.setText("Credencias Incorretas");

        jPassword.setForeground(new java.awt.Color(204, 204, 204));
        jPassword.setText("Password");
        jPassword.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                jPasswordFocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPassword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jEntrar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jErro)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jErro)
                .addGap(18, 18, 18)
                .addComponent(jEntrar)
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jEntrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jEntrarActionPerformed
    {//GEN-HEADEREND:event_jEntrarActionPerformed
        /*if(!Controller.Login(jUsername.getText(), jPassword.getText()))
            jErro.setVisible(true);*/
    }//GEN-LAST:event_jEntrarActionPerformed

    private void jUsernameMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jUsernameMouseClicked
    {//GEN-HEADEREND:event_jUsernameMouseClicked
        if (UserFirst) {
            jUsername.setText("");
        }
        jUsername.setForeground(Color.BLACK);
        UserFirst = false;
    }//GEN-LAST:event_jUsernameMouseClicked

    private void jPasswordFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jPasswordFocusGained
    {//GEN-HEADEREND:event_jPasswordFocusGained
        if (PassFirst) {
            jPassword.setText("");
        }

        jPassword.setForeground(Color.BLACK);
        jPassword.setEchoChar('•');
        PassFirst = false;
    }//GEN-LAST:event_jPasswordFocusGained

    private void jUsernameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jUsernameActionPerformed
    {//GEN-HEADEREND:event_jUsernameActionPerformed

    }//GEN-LAST:event_jUsernameActionPerformed

    private void jUsernameFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jUsernameFocusGained
    {//GEN-HEADEREND:event_jUsernameFocusGained
        if (UserFirst) {
            jUsername.setText("");
        }
        jUsername.setForeground(Color.BLACK);
        UserFirst = false;
    }//GEN-LAST:event_jUsernameFocusGained

    private void jEntrarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jEntrarMouseClicked
    {//GEN-HEADEREND:event_jEntrarMouseClicked

        int ret=ObservableGame.Login(jUsername.getText().trim(), jPassword.getText().trim());
        if (ret==0) {
            jErro.setText("Credenciais Incorretas!");
            jErro.setVisible(true);
        } else if(ret==1) 
        {
            CardLayout cl = (CardLayout) CardPanel.getLayout();
            cl.next(CardPanel);
            RegistoLoginView.setSize(Constants.DIM_X_FRAME,Constants.DIM_Y_FRAME);
        }
        else
        {
            jErro.setText("Verifique a sua Conencção à Internet");
            jErro.setVisible(true);
        }
    }//GEN-LAST:event_jEntrarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jEntrar;
    private javax.swing.JLabel jErro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jUsername;
    // End of variables declaration//GEN-END:variables
}
