/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente.ui.gui.EcraInicial;

import Cliente.logic.ObservableGame;
import classescomunicacao.Constantes;
import static classescomunicacao.Constantes.PEDIDO_ACEITE;
import classescomunicacao.FormarPar;

/**
 *
 * @author Tiago Coutinho
 */
public class PedidoPar extends javax.swing.JPanel
{
    private FormarPar pedidoPar;
    private EcraPrincipal ecraPrincipal;
    private ObservableGame observableGame;
    
    public PedidoPar(ObservableGame observableGame,String nome, EcraPrincipal ecraPrincipal, FormarPar pedidoPar)
    {
        this.observableGame=observableGame;
        this.ecraPrincipal=ecraPrincipal;
        this.pedidoPar=pedidoPar;
        initComponents();
        jUsername.setText(nome);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jUsername = new javax.swing.JLabel();
        jAceitar = new javax.swing.JButton();
        jRejeitar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 102, 102));

        jUsername.setText("Nome Utilizador:");

        jAceitar.setText("Aceitar");
        jAceitar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jAceitarMouseClicked(evt);
            }
        });
        jAceitar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jAceitarActionPerformed(evt);
            }
        });

        jRejeitar.setText("Rejeitar");
        jRejeitar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jRejeitarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jUsername)
                .addGap(18, 18, 18)
                .addComponent(jAceitar)
                .addGap(18, 18, 18)
                .addComponent(jRejeitar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUsername)
                    .addComponent(jAceitar)
                    .addComponent(jRejeitar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jAceitarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jAceitarActionPerformed
    {//GEN-HEADEREND:event_jAceitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAceitarActionPerformed

    private void jAceitarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jAceitarMouseClicked
    {//GEN-HEADEREND:event_jAceitarMouseClicked
        observableGame.EnviaConfirmacao(pedidoPar, PEDIDO_ACEITE);
        observableGame.RemoveAllPar();
        this.setVisible(false);
    }//GEN-LAST:event_jAceitarMouseClicked

    private void jRejeitarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jRejeitarMouseClicked
    {//GEN-HEADEREND:event_jRejeitarMouseClicked
        observableGame.EnviaConfirmacao(pedidoPar, Constantes.PEDIDO_RECUSADO);
        observableGame.RemovePar(pedidoPar);
        this.setVisible(false);
    }//GEN-LAST:event_jRejeitarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAceitar;
    private javax.swing.JButton jRejeitar;
    private javax.swing.JLabel jUsername;
    // End of variables declaration//GEN-END:variables
}
